name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configurar GitHub Pages
        uses: actions/configure-pages@v1

      - name: Subir artefactos para Pages
        uses: actions/upload-pages-artifact@v1
        with:
          path: .

      - name: Desplegar GitHub Pages
        uses: actions/deploy-pages@v1
