name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Cambia si tu rama principal es "master"

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar GitHub Pages
        uses: actions/configure-pages@v4

      - name: Subir archivos (nuevo método)
        uses: actions/upload-pages-artifact@v4
        with:
          path: .  # Publica desde la raíz del proyecto

      - name: Desplegar a GitHub Pages
        uses: actions/deploy-pages@v4
