name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # o 'master' si ese es tu branch principal

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar GitHub Pages
        uses: actions/configure-pages@v4

      - name: Subir archivos
        uses: actions/upload-pages-artifact@v2
        with:
          path: .  # Publica todo desde la raíz del repo

      - name: Desplegar a GitHub Pages
        uses: actions/deploy-pages@v3
